version: '3.1'
services:
  awesome-scrambler:
    image

  email-gmail:
    image

  database:
    image: mongo:latest
    restart: always
    container_name: my-mongo-container
    environment:
      MONGO_INITDB_DATABASE: storage
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"